spring:
  datasource:
    url: jdbc:mysql://rm-2ev56834f7v58862g.mysql.rds.aliyuncs.com/camunda
    username: camunda
    password: 8_+C3vD@Z5ykJ#7B
    driver-class-name: com.mysql.cj.jdbc.Driver
camunda.bpm:
  admin-user:
    id: admin
    password: 123456
    firstName: admin
  filter:
    create: All tasks
  database:
    type: mysql
    schema-update: true
  auto-deployment-enabled: false
